import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_nav/page";
import CartContextProvider from "@/context/cart";
import AuthContextProvider from '../context/Auth'
import WishListProvider from "@/context/wishList";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <AuthContextProvider >
          <WishListProvider>
            <CartContextProvider>
              <Navbar />
              {children}
            </CartContextProvider>
          </WishListProvider>
        </AuthContextProvider>

      </body>
    </html>
  );
}
